"""
Shared state definition for the multi-agent workflow.

The state represents the complete context that flows through all agents:
- issue: The bug/feature request description
- code_context: The source code being analyzed
- plan: The fix strategy generated by planner
- patch: The corrected code generated by writer
"""

from typing import TypedDict


class AgentState(TypedDict):
    """
    Shared state across all agents in the workflow.
    
    Each agent reads from state, processes data, and updates specific fields.
    This ensures clean separation of concerns and clear data flow.
    """
    issue: str          # User's bug description or feature request
    code_context: str   # Source code read from repository
    plan: str          # Fix strategy and approach
    patch: str         # Generated corrected code
